name: Build iOS Demo

on:
  workflow_dispatch:
  push:
    paths:
      - "examples/ios/**"
      - ".github/workflows/build-ios-demo.yml"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve Swift Package dependencies
        run: |
          cd examples/ios/EditJudgeDemo
          if [ -d EditJudgeDemo.xcodeproj ] || [ -f Package.swift ]; then
            xcodebuild -resolvePackageDependencies
          else
            echo "No Xcode project or Swift package found; skipping dependency resolution."
          fi

      - name: Build SwiftUI demo (debug)
        run: |
          cd examples/ios/EditJudgeDemo
          if [ -d EditJudgeDemo.xcodeproj ]; then
            xcodebuild \
              -scheme EditJudgeDemo \
              -destination "platform=iOS Simulator,OS=17.2,name=iPhone 15" \
              build
          elif [ -f Package.swift ]; then
            xcodebuild \
              -scheme EditJudgeDemo \
              -destination "platform=iOS Simulator,OS=17.2,name=iPhone 15" \
              build
          else
            echo "No build target detected; skipping until the demo stub is added."
          fi

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: EditJudgeDemo-build-logs
          path: examples/ios/EditJudgeDemo/build/Logs/**/*.log
          if-no-files-found: ignore
